In [152]:
import numpy as np
import pandas as pd
import json

import requests
from pandas.io.json import json_normalize
import matplotlib.cm as cm
import matplotlib.colors as colors
from sklearn.cluster import KMeans
import folium

from geopy.geocoders import Nominatim
!pip install geopy
!pip install html5lib
!pip install lxml
!pip install BeautifulSoup4

print('librariers are imported')

Requirement already satisfied: geopy in /home/jupyterlab/conda/envs/python/lib/python3.6/site-packages (2.1.0)
Requirement already satisfied: geographiclib<2,>=1.49 in /home/jupyterlab/conda/envs/python/lib/python3.6/site-packages (from geopy) (1.50)
Requirement already satisfied: html5lib in /home/jupyterlab/conda/envs/python/lib/python3.6/site-packages (0.9999999)
Requirement already satisfied: six in /home/jupyterlab/conda/envs/python/lib/python3.6/site-packages (from html5lib) (1.15.0)
Requirement already satisfied: lxml in /home/jupyterlab/conda/envs/python/lib/python3.6/site-packages (4.6.2)
Requirement already satisfied: BeautifulSoup4 in /home/jupyterlab/conda/envs/python/lib/python3.6/site-packages (4.9.3)
Requirement already satisfied: soupsieve>1.2; python_version >= "3.0" in /home/jupyterlab/conda/envs/python/lib/python3.6/site-packages (from BeautifulSoup4) (2.2)
librariers are imported

In [177]:
from pandas.io.html import read_html
url ='https://en.wikipedia.org/wiki/List_of_postal_codes_of_Canada:_M'
toronto_data = read_html(url, attrs={"class":"wikitable"})
print('Data downloaded!')

Data downloaded!

In [178]:
toronto_data[0]

,Postal Code,Borough,Neighbourhood
0,M1A,Not assigned,Not assigned
1,M2A,Not assigned,Not assigned
2,M3A,North York,Parkwoods
3,M4A,North York,Victoria Village
4,M5A,Downtown Toronto,"Regent Park, Harbourfront"
...,...,...,...
175,M5Z,Not assigned,Not assigned
176,M6Z,Not assigned,Not assigned
177,M7Z,Not assigned,Not assigned
178,M8Z,Etobicoke,"Mimico NW, The Queensway West, South of Bloor,..."
179,M9Z,Not assigned,Not assigned

In [179]:
toronto_data[0].drop(toronto_data[0].index[toronto_data[0]['Borough'] == 'Not assigned'], inplace=True)

toronto_data[0] = toronto_data[0].reset_index(drop=True)

toronto_data[0]

,Postal Code,Borough,Neighbourhood
0,M3A,North York,Parkwoods
1,M4A,North York,Victoria Village
2,M5A,Downtown Toronto,"Regent Park, Harbourfront"
3,M6A,North York,"Lawrence Manor, Lawrence Heights"
4,M7A,Downtown Toronto,"Queen's Park, Ontario Provincial Government"
...,...,...,...
98,M8X,Etobicoke,"The Kingsway, Montgomery Road, Old Mill North"
99,M4Y,Downtown Toronto,Church and Wellesley
100,M7Y,East Toronto,"Business reply mail Processing Centre, South C..."
101,M8Y,Etobicoke,"Old Mill South, King's Mill Park, Sunnylea, Hu..."
102,M8Z,Etobicoke,"Mimico NW, The Queensway West, South of Bloor,..."

In [180]:
toronto_data=toronto_data[0].groupby('Postal Code').agg(','.join)
toronto_data.head(200)

                 Borough                                      Neighbourhood
Postal Code
M1B          Scarborough                                     Malvern, Rouge
M1C          Scarborough             Rouge Hill, Port Union, Highland Creek
M1E          Scarborough                  Guildwood, Morningside, West Hill
M1G          Scarborough                                             Woburn
M1H          Scarborough                                          Cedarbrae
...                  ...                                                ...
M9N                 York                                             Weston
M9P            Etobicoke                                          Westmount
M9R            Etobicoke  Kingsview Village, St. Phillips, Martin Grove ...
M9V            Etobicoke  South Steeles, Silverstone, Humbergate, Jamest...
M9W            Etobicoke                Northwest, West Humber - Clairville

[103 rows x 2 columns]

In [181]:
toronto_data.replace({'Neighbourhood':'Not Assigned'},(toronto_data['Borough']))

                 Borough                                      Neighbourhood
Postal Code
M1B          Scarborough                                     Malvern, Rouge
M1C          Scarborough             Rouge Hill, Port Union, Highland Creek
M1E          Scarborough                  Guildwood, Morningside, West Hill
M1G          Scarborough                                             Woburn
M1H          Scarborough                                          Cedarbrae
...                  ...                                                ...
M9N                 York                                             Weston
M9P            Etobicoke                                          Westmount
M9R            Etobicoke  Kingsview Village, St. Phillips, Martin Grove ...
M9V            Etobicoke  South Steeles, Silverstone, Humbergate, Jamest...
M9W            Etobicoke                Northwest, West Humber - Clairville

[103 rows x 2 columns]

In [183]:
toronto_data.shape

(103, 2)

In [184]:
importÂ geocoderÂ #Â importÂ geocoder
postal_codeÂ =Â toronto_data['PostalÂ Code']
#Â UsingÂ whileÂ Statement
latitudeÂ =Â []longitudeÂ =Â []nÂ =Â 0
while(lat_lng_coords is None):
  g = geocoder.google('{}, Toronto, Ontario'.format(postal_code))
  lat_lng_coords = g.latlng
print('TheÂ geograpicalÂ coordinateÂ ofÂ {}Â areÂ {},Â {}.'.format(postal_code[n],Â lat_
lng_coords[0],Â lat_lng_coords[1]))
    latitude.append(lat_lng_coords[0])Â Â Â Â 
    longitude.append(lat_lng_coords[1])Â Â Â Â 
    nÂ =Â nÂ +Â 1
    
toronto_data['Latitude']Â =Â latitude
toronto_data['Longitude']Â =Â longitude
toronto_data.head(12)

SyntaxError: invalid character in identifier (<ipython-input-184-3584e07f7f45>, line 1)